# Generated by Django 4.2.4 on 2023-11-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPrdt',
            fields=[
                ('dcls_month', models.CharField(max_length=10)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=200)),
                ('fin_prdt_cd', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=200, null=True)),
                ('mtrt_int', models.CharField(max_length=200)),
                ('spcl_cnd', models.CharField(max_length=200, null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.CharField(max_length=1000, null=True)),
                ('etc_note', models.CharField(max_length=200, null=True)),
                ('max_limit', models.CharField(max_length=200, null=True)),
                ('dcls_strt_day', models.CharField(max_length=20)),
                ('dcls_end_dat', models.CharField(max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=200)),
                ('intr_rate_type_nm', models.CharField(max_length=200, null=True)),
                ('save_trm', models.CharField(max_length=200)),
                ('intr_rate', models.CharField(max_length=200, null=True)),
                ('intr_rate2', models.CharField(max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='fin_prct_recom.financialprdt')),
            ],
        ),
    ]
