# Generated by Django 4.2.4 on 2023-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_prct_recom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositloanoptions',
            name='lend_rate_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='depositloanoptions',
            name='lend_rate_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='financialoptions',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='financialoptions',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='houseloanoptions',
            name='lend_rate_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='houseloanoptions',
            name='lend_rate_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='houseloanprdt',
            name='loan_lmt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='rsrv_type_nm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yearsavingprdt',
            name='btrm_prft_rate_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='yearsavingprdt',
            name='btrm_prft_rate_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='yearsavingprdt',
            name='btrm_prft_rate_3',
            field=models.FloatField(null=True),
        ),
    ]
