# Generated by Django 4.2.4 on 2023-11-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_prct_recom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositloanprdt',
            name='loan_inci_expn',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
