# Generated by Django 4.2.4 on 2023-12-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_prct_recom', '0002_remove_depositloanoptions_lend_rate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearsavingoptions',
            name='pnsn_recp_amt',
            field=models.IntegerField(null=True),
        ),
    ]
