# Generated by Django 4.2.4 on 2023-11-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_prct_recom', '0003_alter_houseloanprdt_loan_lmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='rsrv_type_nm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='save_trm',
            field=models.IntegerField(null=True),
        ),
    ]
