# Generated by Django 4.2.4 on 2023-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_prct_recom', '0003_userjoinprdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoinprdt',
            name='product',
            field=models.TextField(null=True),
        ),
    ]
