# Generated by Django 4.2.4 on 2023-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_prct_recom', '0004_alter_userjoinprdt_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinprdt',
            name='product_type',
            field=models.TextField(null=True),
        ),
    ]
